### ISSUE TITLE
Setting Up Final Capstone Kanban Board.

### ISSUE THREAD

**Issue by billionsjoel** [billionsjoel/dravel-app#13]
**In this Issue:**

- We are four (4) team members developing the dravel app.
- @billionsjoel , @joskalenda , @Anny85-code  and @abdessalem1998 
- [Here](https://github.com/billionsjoel/dravel-app/projects/1) is the link to our project kanban board
- Attached is a screenshot for our kanban board.
<img width="1916" alt="Screenshot 2022-06-01 at 16 35 51" src="https://user-images.githubusercontent.com/15736819/171418139-e5531136-529b-45cd-8672-c2db1e7633c2.png">

**Comment by MuriloRoque** [comment]
Hi @billionsjoel, @joskalenda, @Anny85-code, @abdessalem1998,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by billionsjoel** [comment]
Thank you so much @MuriloRoque 👍

 <img src="https://media0.giphy.com/media/kyLYXonQYYfwYDIeZl/giphy.gif"/>
